FROM golang:1.19-alpine AS builder

ARG TARGETOS TARGETARCH

ENV CGO_ENABLED=1

RUN apk add --no-cache \
    libpcap-dev \
    g++ \
    perl-utils \
    curl \
    build-base \
    binutils-gold \
    bash \
    clang \
    llvm \
    libbpf-dev \
    linux-headers \
    git

ARG GITUSER
ARG GITPAT
ARG GITAPITOKEN
ARG VERSION

RUN go env -w GOPRIVATE=github.com/mogenius
RUN git config --global url."https://$GITUSER:$GITPAT@github.com".insteadOf "https://github.com"

WORKDIR /app

COPY . .

RUN ./build-client.sh NEXT_VERSION=$VERSION GOOS=darwin GOARCH=amd64 github_api_token=$GITAPITOKEN
RUN ./build-client.sh NEXT_VERSION=$VERSION GOOS=darwin GOARCH=arm64 github_api_token=$GITAPITOKEN

RUN ./build-client.sh NEXT_VERSION=$VERSION GOOS=linux GOARCH=386 github_api_token=$GITAPITOKEN
RUN ./build-client.sh NEXT_VERSION=$VERSION GOOS=linux GOARCH=arm64 github_api_token=$GITAPITOKEN
RUN ./build-client.sh NEXT_VERSION=$VERSION GOOS=linux GOARCH=amd64 github_api_token=$GITAPITOKEN


RUN ./build-client.sh NEXT_VERSION=$VERSION GOOS=windows GOARCH=arm64 github_api_token=$GITAPITOKEN
RUN ./build-client.sh NEXT_VERSION=$VERSION GOOS=windows GOARCH=amd64 github_api_token=$GITAPITOKEN